workflows:
  ios-free-build:
    name: iOS Free Accounts Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter packages pub get
      - name: Install Pods and Build
        script: |
          # 1. I-generate ang kailangang iOS files
          flutter precache --ios
          
          # 2. Build ios nang walang codesign
          flutter build ios --release --no-codesign
          
          # 3. Packaging logic
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../unsigned_app.ipa Payload
    artifacts:
      - "*.ipa"