platform :ios, '14.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Inalis natin ang flutter_install_all_ios_pods dahil ito ang naghahanap ng podhelper.rb
  # Sa halip, hayaan natin ang Codemagic na mag-inject ng plugins
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      # Mahalaga ito para sa mga architecture errors sa M2 machine
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end
end