platform :ios, '14.0'

# HANAPIN ANG FLUTTER SDK PATH
# Sa Codemagic machine, ang Flutter ay nasa default path na ito:
flutter_root = ENV['FLUTTER_ROOT'] || File.expand_path('~/programs/flutter')
podhelper_path = File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

if File.exist?(podhelper_path)
  load podhelper_path
else
  # Fallback path kung iba ang setup ng machine
  load File.expand_path(File.join('..', '..', 'flutter', 'bin', 'cache', 'artifacts', 'engine', 'ios', 'Frameworks', 'podhelper.rb'), __FILE__)
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end