# Import ang Flutter helper script
load File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __FILE__)

platform :ios, '14.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Dito ini-install ang dependencies gaya ng Google Maps
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Pinupwersa ang lahat ng plugins sa iOS 14.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end